# Generated by Django 5.0.2 on 2024-04-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="LostAndFoundCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Lost and Found Category",
                "verbose_name_plural": "Lost and Found Categories",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Marketplace Category",
                "verbose_name_plural": "Marketplace Categories",
            },
        ),
        migrations.CreateModel(
            name="LostAndFoundModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="lost_and_found")),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_and_found"
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_and_found"
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_and_found"
                    ),
                ),
                ("contact", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.lostandfoundcategorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lost and Found",
                "verbose_name_plural": "Lost and Founds",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="marketplace")),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="marketplace"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="marketplace"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="marketplace"),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("contact", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.marketplacecategorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Item",
                "verbose_name_plural": "Marketplace Items",
            },
        ),
        migrations.CreateModel(
            name="RideShareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location", models.CharField(max_length=100)),
                ("end_location", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="ride_share")),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="ride_share"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="ride_share"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="ride_share"),
                ),
                ("available_seats", models.IntegerField()),
                ("total_seats", models.IntegerField()),
                ("contact", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Share",
                "verbose_name_plural": "Ride Shares",
            },
        ),
        migrations.CreateModel(
            name="RoomFinderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="room_finder")),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="room_finder"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="room_finder"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="room_finder"),
                ),
                ("location", models.CharField(max_length=100)),
                ("no_of_availability", models.IntegerField()),
                ("available_from", models.DateField()),
                ("room_type", models.CharField(max_length=100)),
                (
                    "prefered_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stay_type",
                    models.CharField(
                        choices=[
                            ("Short Term", "Short Term"),
                            ("Long Term", "Long Term"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "smoking_preference",
                    models.CharField(
                        choices=[
                            ("Non-Smoker", "Non-Smoker"),
                            ("Outside Only", "Outside Only"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vegetarian_preference",
                    models.CharField(
                        choices=[
                            ("Vegetarian", "Vegetarian"),
                            ("Non-Vegetarian", "Non-Vegetarian"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pet_preference",
                    models.CharField(
                        choices=[
                            ("No Pets", "No Pets"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alcohol_preference",
                    models.CharField(
                        choices=[
                            ("No Alcohol", "No Alcohol"),
                            ("Doesn't Matter", "Doesn't Matter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Finder",
                "verbose_name_plural": "Room Finders",
            },
        ),
    ]
